# Generated by Django 5.0.4 on 2024-05-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techapp', '0002_rename_contact_loging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
