# Generated by Django 5.0.4 on 2024-05-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loging',
            new_name='Contact',
        ),
    ]
